apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-micro-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-micro-service
  template:
    metadata:
      labels:
        app: second-micro-service
    spec:
      containers:
        - image: amihevc/kosarica-slika
          name: second-micro-service
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              valueFrom:
                secretKeyRef:
                  name: db-kosarica-pass
                  key: connectionurl
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-kosarica-pass
                  key: username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-kosarica-pass
                  key: password
          ports:
            - containerPort: 8081
              name: server2
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: second-micro-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server2
  selector:
    app: second-micro-service
