kumuluzee:
  name: first-micro-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/first-micro-service
      username: dbuser
      password: postgres
      max-pool-size: 20
rest-properties:
  maintenance-mode: false
